In [1]:
import math

nums = [2.786,4.678,5.456,6.784,7.349]
print(nums)
total = sum(nums)
max_num = max(nums)
minimum = min(nums)
length = len(nums)
avg = total / length
sqrt_list = [round(math.sqrt(num), 2) for num in nums]
rounded_list0 = [round(num) for num in nums]
rounded_list2 = [round(num,2) for num in nums]
print("Sum: ", total)
print("Max: ", max_num)
print("Min: ", minimum)
print("Len: ", length)
print("Avg: ", avg)
print("Sqrt: ", sqrt_list)
print("Rounded to 0: ", rounded_list0)
print("Rounded to 2: ", rounded_list2)

[2.786, 4.678, 5.456, 6.784, 7.349]
Sum:  27.053
Max:  7.349
Min:  2.786
Len:  5
Avg:  5.4106000000000005
Sqrt:  [1.67, 2.16, 2.34, 2.6, 2.71]
Rounded to 0:  [3, 5, 5, 7, 7]
Rounded to 2:  [2.79, 4.68, 5.46, 6.78, 7.35]


Implementing Matrix addition, subtraction, multiplication, inverse, transpose and
division operations using vectors using numpy

In [1]:
import numpy as np

array = np.zeros((3, 4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:


A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

addition = A + B
subtraction = A - B
multiplication = np.dot(A, B)
transpose = np.transpose(A)
inverse = np.linalg.inv(A) if np.linalg.det(A) != 0 else "Not invertible"
division = np.divide(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("NumPy Operations:")
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Transpose:\n", transpose)
print("Inverse of A:\n", inverse)
print("Division:\n", division)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
NumPy Operations:
Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
